export const INIT_CONSUMPTIONS = 'INIT_CONSUMPTIONS';
export const CREATE_CONSUMPTION = 'CREATE_CONSUMPTION';
export const UPDATE_CONSUMPTION = 'UPDATE_CONSUMPTION';
export const DELETE_CONSUMPTION = 'DELETE_CONSUMPTION';

export const INIT_CATEGORIES = 'INIT_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const GET_BUDGETS_LIST = 'GET_BUDGETS_LIST';
export const SET_BUDGET = 'SET_BUDGET';

export const UPDATE_MONEY_LEFT = 'UPDATE_MONEY_LEFT';

export const INIT_MONTHLY_CHART = 'INIT_MONTHLY_CHART';
export const INIT_MONTHLY_TABLE = 'INIT_MONTHLY_TABLE';
export const INIT_MONTHLY_BY_CATEGORY = 'INIT_MONTHLY_BY_CATEGORY';
export const INIT_BUDGET_CHART = 'INIT_BUDGET_CHART'