export const GET_CONSUMPTIONS_LIST = 'GET_CONSUMPTIONS_LIST';
export const CREATE_CONSUMPTION = 'CREATE_CONSUMPTION';
export const UPDATE_CONSUMPTION = 'UPDATE_CONSUMPTION';
export const DELETE_CONSUMPTION = 'DELETE_CONSUMPTION';

export const GET_CATEGORIES_LIST = 'GET_CATEGORIES_LIST';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const GET_BUDGETS_LIST = 'GET_BUDGETS_LIST';
export const GET_CURRENT_BUDGET = 'GET_CURRENT_BUDGET';
export const CREATE_BUDGET = 'CREATE_BUDGET';
export const DELETE_BUDGET = 'DELETE_BUDGET';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';

export const UPDATE_MONEY_LEFT = 'UPDATE_MONEY_LEFT';

export const GET_CHARTS_DATA_REQUEST = 'GET_CHARTS_DATA_REQUEST';
export const GET_CHARTS_DATA_SUCCESS = 'GET_CHARTS_DATA_SUCCESS';
export const GET_CHARTS_DATA_ERROR = 'GET_CHARTS_DATA_ERROR';
